<?php

namespace NG\HomeBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class ImageType extends FileType {
    public function getParent()
    {
        return 'file';
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars['preview_width'] = $form->getConfig()->getOption('preview_width', 120);
        $view->vars['preview_class'] = $form->getConfig()->getOption('preview_class', 0);
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'uri' => '',
            'preview_width' => 0,
            'preview_class' => 'preview'
        ));
        parent::setDefaultOptions($resolver); // TODO: Change the autogenerated stub
    }


    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName()
    {
        return 'image';
    }
}